# Overwrite base URL for assets. Useful when hosting files in any location other than the root
base_url="/"

# Folder where the source markdown files are located
source_folder="./docs/"

# Folder where the generated HTML files should be saved
output_folder="./public/"

# Folder where site theme handlebars templates are located
theme_folder="./default-theme/"

# Path to asset processing file. Optional.
asset_pipeline_file="./asset-pipeline.js"

# Can disable doc index generation even when index.md is present
# default: false
generate_doc_index=false

# Include version in the URL
# default: true
enable_versions=true

# Documentation version (files will be nested in this folder)
# e.g. "0.0.1", "stable", "main"
version_to_publish="main"

# When enabled the first folder level are the locales roots
# and each locale root has independent navigation
# default: true
enable_locales=true

# Default site locale. Used in doc index and when enable locales is disabled
default_locale="en"

# Prefix for anchors generated by Shromp. By default, an id is generated for every heading
# so navigation links can point to the correct section of the page.
#This property defines a prefix to reduce the chance of conflict with user defined anchors.
anchor_prefix="sp-"
