###################################
# SHROMP THEME CONFIG
# Created by: Vinicius Gerevini <thisisvini.com>
###################################

# Default template used for pages
default_template="page"
