
title = "Shromp"
description = "A chill static site/docs generator that shrimply works"
keywords="site generator,static site"
image = "/assets/images/icon.png"
url="https://thisisvini.com/shromp"

# [locales.en]
# title = "Shromp in English"
# description = ""
# keywords="site generator,static site"
# image = "icon.png"
